name: Docker Multi-Arch Build and Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '42 0 * * *' # Daily check for base image updates

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: derphilipp/caddy_plus:latest
          platforms: linux/amd64,linux/arm64

